// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/main-resume": {
    params: {};
  };
  "/job-posting/:id": {
    params: {
      "id": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/main-resume" | "/job-posting/:id";
  };
  "routes/main-resume.tsx": {
    id: "routes/main-resume";
    page: "/";
  };
  "routes/main-resume.redirect.tsx": {
    id: "routes/main-resume.redirect";
    page: "/main-resume";
  };
  "routes/job-posting.$id.tsx": {
    id: "routes/job-posting.$id";
    page: "/job-posting/:id";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/main-resume": typeof import("./app/routes/main-resume.tsx");
  "routes/main-resume.redirect": typeof import("./app/routes/main-resume.redirect.tsx");
  "routes/job-posting.$id": typeof import("./app/routes/job-posting.$id.tsx");
};